name: 'stock_market_dbt'
version: '1.0.0'
config-version: 2

profile: 'stock_market_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  batch_database: STOCKMARKETBATCH
  stream_database: STOCKMARKETSTREAM
  batch_schema: PUBLIC
  stream_schema: PUBLIC

models:
  stock_market_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
