version: 2

sources:
  - name: snowflake_batch
    description: >
      Raw historical daily stock data loaded by the Spark batch pipeline
      into STOCKMARKETBATCH. These tables are the entry point for all
      batch-based dbt transformations.
    database: STOCKMARKETBATCH
    schema: PUBLIC
    freshness:
      warn_after: {count: 25, period: hour}
      error_after: {count: 49, period: hour}
    loaded_at_field: BATCH_LOAD_TIMESTAMP

    tables:
      - name: DAILY_STOCK_METRICS
        description: >
          Daily OHLCV (Open, High, Low, Close, Volume) stock metrics loaded
          by load_to_snowflake.py after Spark batch processing.
        columns:
          - name: SYMBOL
            description: Stock ticker symbol (e.g. AAPL, MSFT)
            tests:
              - not_null
          - name: DATE
            description: Trading date
            tests:
              - not_null
          - name: DAILY_OPEN
            description: Opening price for the trading day
          - name: DAILY_HIGH
            description: Highest price during the trading day
          - name: DAILY_LOW
            description: Lowest price during the trading day
          - name: DAILY_CLOSE
            description: Closing price for the trading day
            tests:
              - not_null
          - name: DAILY_VOLUME
            description: Total shares traded during the day
          - name: BATCH_LOAD_TIMESTAMP
            description: Timestamp when the record was loaded into Snowflake

  - name: snowflake_stream
    description: >
      Real-time streaming stock analytics loaded by the Spark streaming pipeline
      into STOCKMARKETSTREAM. Contains windowed aggregations and moving averages
      computed during live market hours.
    database: STOCKMARKETSTREAM
    schema: PUBLIC
    freshness:
      warn_after: {count: 2, period: hour}
      error_after: {count: 6, period: hour}
    loaded_at_field: LOAD_TIMESTAMP

    tables:
      - name: REALTIME_STOCK_ANALYTICS
        description: >
          Real-time sliding window analytics (15-min and 1-hour windows)
          loaded by load_stream_to_snowflake.py after Spark structured streaming.
        columns:
          - name: SYMBOL
            description: Stock ticker symbol
            tests:
              - not_null
          - name: WINDOW_START
            description: Start of the analytics window
            tests:
              - not_null
          - name: WINDOW_END
            description: End of the analytics window
          - name: MA_15M
            description: 15-minute moving average price
          - name: MA_1H
            description: 1-hour moving average price
          - name: VOLATILITY_15M
            description: Price volatility (std dev) over the 15-minute window
          - name: VOLUME_SUM_15M
            description: Total volume traded in the 15-minute window
          - name: LOAD_TIMESTAMP
            description: Timestamp when record was loaded into Snowflake
